spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/expense_manager
  username: postgres
  password: Password123
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: create
  properties:
   hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
   
   
